icon: ':simple-bitwarden:'
cit:
  mode: screenshot
  port: 80
build:
  pkg_name: vaultwarden
  variants:
    - tag: pkg
      containerfile: Containerfile.pkg
      aliases: ["latest"]
      default: true
    - tag: pkg-latest
      containerfile: Containerfile.pkg
      args:
        BASE_VERSION: "15-latest"
